{"name": "test_login_correct_loginFaiul", "status": "failed", "start": 1699425583204, "stop": 1699425583204, "uuid": "95630184-3c0b-4723-831b-a032de23e85e", "historyId": "1df25cb598586ffedeb9257135b7cf01", "testCaseId": "1df25cb598586ffedeb9257135b7cf01", "fullName": "test.test_login.Test_login#test_login_correct_loginFaiul", "labels": [{"name": "tag", "value": "@pytest.mark.xfail(reason='标记这个用例为失败用例')"}, {"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_login"}, {"name": "host", "value": "DESKTOP-FRO1ATK"}, {"name": "thread", "value": "20248-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_login"}]}